--- !ditz.rubyforge.org,2008-03-06/project 
name: tinyback
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: tinyback
- !ditz.rubyforge.org,2008-03-06/component 
  name: Services
- !ditz.rubyforge.org,2008-03-06/component 
  name: Reaper
- !ditz.rubyforge.org,2008-03-06/component 
  name: Postprocessing
releases: []

