--- !ditz.rubyforge.org,2008-03-06/project 
name: tinyback
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: tinyback
- !ditz.rubyforge.org,2008-03-06/component 
  name: Services
- !ditz.rubyforge.org,2008-03-06/component 
  name: Reaper
- !ditz.rubyforge.org,2008-03-06/component 
  name: Postprocessing
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: Runable version
  status: :unreleased
  release_time: 
  log_events: 
  - - 2010-12-04 23:13:21.493667 Z
    - David Triendl <david@triendl.name>
    - created
    - This milestone tracks bug that are so serious that all scraping operations have to be put on hold until they are fixed.
- !ditz.rubyforge.org,2008-03-06/release 
  name: v0.1
  status: :unreleased
  release_time: 
  log_events: 
  - - 2011-02-23 05:31:30.168616 Z
    - David Triendl <david@triendl.name>
    - created
    - This is the first polished version that can be released to the public.
